#! /usr/bin/env python

import os

root_dir = "/srv/git"
repos = {}
for repo_name in os.listdir(root_dir):
    description = os.path.join(root_dir, repo_name, 'description')
    with open(description, 'ro') as f:
        for line in f:
            print '{0} .... {1}'.format(repo_name, line)
            break
