#! /usr/bin/env python

import os

root_dir = "/srv/git"
repos = {}
for repo_name in os.listdir(root_dir):
    description = os.path.join(root_dir, repo_name, 'description')
    with open(description, 'ro') as f:
        for line in f:
            repos[repo_name] = line
            break

for k,v in sorted(repos.items()):
    print '{0} .... {1}'.format(k, v),
