#!/bin/bash

source repo_env
set -e

REPO_NAME=$1
if [ -z ${REPO_NAME} ]
then
	echo "No repo specified"
	exit 1
fi

REPO_PATH=""${GIT_DIR}"/"${REPO_NAME}".git"
if [ -d "${REPO_PATH}" ]
then
	rm -r ${REPO_PATH}
	echo "Repository "${REPO_NAME}" deleted"
	exit 0
else
	echo "Repository "${REPO_NAME}" not found"
	exit 1
fi
