#!/bin/bash

source repo_env
set -e

REPO_NAME=$1
if [ -z ${REPO_NAME} ]
then
	echo "No repo specified"
	exit 1
fi

REPO_PATH=""${GIT_DIR}"/"${REPO_NAME}".git"
if [ -d "${REPO_PATH}" ]
then
	echo -n "Are you sure you want to delete repo "${REPO_NAME}"? (Y/N) "
	read response
	if [ ${response^^} == 'Y' ]
	then
		rm -r ${REPO_PATH}
	elif [ ${response^^} == 'N' ]
	then
		exit 0
	else
		echo "Invalid repsonse given, repository retained"
		exit 0
	fi
	echo "Repository "${REPO_NAME}" deleted"
	exit 0
else
	echo "Repository "${REPO_NAME}" not found"
	exit 1
fi
