#!/bin/bash

set -e

source repo_env

REPO_NAME=$1
if [ -z ${REPO_NAME} ]
then
	echo "No repo specified"
	exit 1
fi

REPO_PATH=""${PI_GIT_DIR}"/"${REPO_NAME}".git"

if [ -d "${REPO_PATH}" ]
then
	echo "${REPO_NAME} already exists, aborting"
	exit 1
else
	mkdir -p "${REPO_PATH}"
	cd ${REPO_PATH}
	git init --bare --shared > /dev/null
	echo "Git repository ${REPO_NAME} created"
	echo $2 > description
	cd - >/dev/null
	exit 0
fi
